### ISSUE TITLE
Creating "gh-pages" if not exists

### ISSUE THREAD

**Issue by demiurg906** [demiurg906/conspectus-framework#9]
Надо генерить `gh-pages` ветку в скрипте по клонированию репы, если ее (ветки) еще нет

**Comment by xamgore** [comment]
Хм, а раньше ж вроде так и было, не?
`git checkout -b gh_pages ...`

**Comment by demiurg906** [comment]
нет, эту строчку я не трогал
`git clone "https://${GH_TOKEN}@github.com/${1}.git" --branch gh-pages --depth=1 ./_site`

если я правильно помню, `git checkout -b` именно что создает новую ветку, если она уже есть, то он ругается
надо понять, что если он ругается, то надо делать просто `checkout`, без `-b`
а я bash скрипты не люблю

**Comment by xamgore** [comment]
Если честно, то я немного не понял всё равно. В эту ветку пушится скомпилированный сайт потом? Или как она используется? Если ветки не было, какую работу надо выполнить?

Завтра гляну, просто отпишись в этот тред. Уже примерно представляю решение.

**Comment by demiurg906** [comment]
Если есть `gh-pages`, то надо юзать текущий вариант
если нет (т.е это первый билд), то надо сделать что-то вроде
```
git clone ... (клонируем master)
git checkout -b gh-pages
```
